spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: nacos:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: route_user_service #http://localhost/user/users
          uri: lb://gateway-user-service
          predicates:
            - Path=/user/** #localhost:80/user/users -> http://gateway-user-service/user/users 404
            - TokenHeader=Token
          filters:
            - StripPrefix=1 #localhost:80/user/users -> http://gateway-user-service/users 200
            - RequestLogging
            - ResponseLogging

        - id: route_product_service # http://localhost/product/products
          uri: lb://gateway-product-service
          predicates:
            - Path=/product/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - StripPrefix=1
server:
  port: 80
logging:
  level:
    root: info
