server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://a-db:3306/sakila?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
  application:
    name: a-service